### ISSUE TITLE
docker-compose提示以下错误请帮忙说明是什么情况

### ISSUE THREAD

**Issue by qyweiyy** [masalabs/MASA.EShop#2]
Problems loading reference 'https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json': Unable to load schema from 'https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json': unable to verify the first certificate.		xxxxx\docker-compose.yml

**Comment by MayueCif** [comment]
你这个提示我也不能确认是什么问题，是执行`docker-compose up --build`提示的错误吗。Unable to load 或者是网络问题造成的

**Comment by MayueCif** [comment]
> Problems loading reference 'https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json': Unable to load schema from 'https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json': unable to verify the first certificate. xxxxx\docker-compose.yml

你这个提示我也不能确认是什么问题，是执行docker-compose up --build提示的错误吗。Unable to load 或者是网络问题造成的

**Comment by zhenlei520** [comment]
> > Problems loading reference 'https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json': Unable to load schema from 'https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json': unable to verify the first certificate. xxxxx\docker-compose.yml
> 
> 你这个提示我也不能确认是什么问题，是执行docker-compose up --build提示的错误吗。Unable to load 或者是网络问题造成的

After I annotated the related configuration of masa.eshop.web.client in docker-compose.yml, it can start normally

**Comment by doddgu** [comment]
No more questions. I just closed it
